version: '3.8'

services:

  app:
    build:
      context: ./app
      dockerfile: dockerfile
    depends_on:
      - server
    ports:
      - "8080:8080"
    container_name: app
    volumes:
    - ./app:/app
    - /app/node_modules
    env_file:
      - ./.env
      - ./secrets.env

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    container_name: server
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./.env
      - ./secrets.env

  db:
    container_name: db
    image: mongo:4.0
    restart: always
